imagePullPolicy: Always
nodeSelector: {}

balancer:
  cookie:
    # SET THIS TO TRUE IF IN PRODUCTION
    # Sets secure Flag in cookie
    secure: false
    # If secure is set to true the cookie name will automatically be prefixed with "__Secure-"
    name: balancer
  repository: iteratec/juice-balancer
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 400m
    limits:
      memory: 256Mi
      cpu: 400m
  affinity: {}
  tolerations: []

juiceShop:
  # Set to -1 to remove the max Juice Shop instance cap
  maxInstances: 10
  # Juice Shop Image to use
  image: bkimminich/juice-shop
  tag: latest
  # Change the key when hosting a CTF event
  # This key gets used to generate the challenge flags
  # See: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/ctf.html#overriding-the-ctfkey
  ctfKey: 'zLp@.-6fMW6L-7R3b!9uR_K!NfkkTr'
  nodeEnv: 'juicy-ctf'
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 200Mi
      cpu: 200m
  # Specify a custom Juice Shop config.yaml
  # See the JuiceShop Config Docs for more detail: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/customization.html#yaml-configuration-file
  # See example customizations: https://github.com/bkimminich/juice-shop/tree/master/config
  config: |
    application:
      logo: JuiceShopCTF_Logo.png
      favicon: favicon_ctf.ico
      # showChallengeHints: false
      showVersionNumber: false
      # showHackingInstructor: false
      gitHubRibbon: false
    ctf:
      # showFlagsInNotifications: true

# Config for the redis deployment
# This is using: https://hub.helm.sh/charts/stable/redis
redis:
  cluster:
    slaveCount: 1
  # OpenShifts Default Security Context makes trouble with the security context
  # of the redis chart. Uncomment the next two lines to have it run on OpenShift.
  # securityContext:
  #   enabled: false

# Deletes unused JuiceShop instances after a configuable period of inactivity
juiceShopCleanup:
  repository: iteratec/juice-cleaner
  tag: latest
  enabled: true
  gracePeriod: 1d
  # cron in which the clean up job is run
  # defaults to once in an hour
  # change this if your grace period if shorter than 1 hour
  cron: '0 * * * *'
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity: {}
  tolerations: []
